---
version: 1

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    LABEL maintainer Validated Patterns <team-validated-patterns@redhat.com>
    RUN cat /etc/os-release
  append:
    # oc and kubectl
    - RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar -xvzf - -C /usr/local/bin/ oc && chmod 755 /usr/local/bin/oc && ln -s /usr/local/bin/oc /usr/local/bin/kubectl
    # helm
    - RUN curl -sSL -o /usr/local/bin/helm https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/helm/3.7.1/helm-linux-amd64 && chmod 755 /usr/local/bin/helm
    # kustomize
    - RUN curl -sLfO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.5/kustomize_v4.5.5_linux_amd64.tar.gz && tar xvf kustomize_v4.5.5_linux_amd64.tar.gz -C /usr/local/bin && rm -f kustomize_v4.5.5_linux_amd64.tar.gz && chmod 755 /usr/local/bin/kustomize
    # yq
    - RUN curl -sSL -o /usr/local/bin/yq  https://github.com/mikefarah/yq/releases/download/v4.25.3/yq_linux_amd64 && chmod 755 /usr/local/bin/yq
    # argocd
    - RUN curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.4.2/argocd-linux-amd64 && chmod 755 /usr/local/bin/argocd
    # tkn
    - RUN curl -sLfO https://github.com/tektoncd/cli/releases/download/v0.24.0/tkn_0.24.0_Linux_x86_64.tar.gz && tar xvf tkn_0.24.0_Linux_x86_64.tar.gz -C /usr/local/bin --no-same-owner && chmod 755 /usr/local/bin/tkn && rm -f /usr/local/bin/README.md && rm -f /usr/local/bin/LICENSE
    # Trim azure install
    - RUN curl -sSL -o /usr/local/bin/azure_sdk_trim.py https://raw.githubusercontent.com/clumio-code/azure-sdk-trim/main/azure_sdk_trim/azure_sdk_trim.py && chmod 755 /usr/local/bin/azure_sdk_trim.py && /usr/local/bin/azure_sdk_trim.py && pip3 uninstall -y humanize
