---
collections:
  - name: ansible.posix
    source: https://galaxy.ansible.com
  - name: oasis_roles.system
    source: https://galaxy.ansible.com
  - name: fedora.linux_system_roles
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: containers.podman
    source: https://galaxy.ansible.com
  - name: community.okd
    source: https://galaxy.ansible.com
  - name: awx.awx
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    source: https://galaxy.ansible.com
  - name: redhat_cop.controller_configuration
    source: https://galaxy.ansible.com
